services:
  - type: web
    name: tds-virtual-ta
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn index:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjI0ZjEwMDE0MzRAZHMuc3R1ZHkuaWl0bS5hYy5pbiJ9.wiIIK6cwuUov-byzc0XMbszr0AqW2_F-TSQmfStxfn8
      - key: OPENAI_BASE_URL
        value: https://aipipe.org/openai/v1
